name: Build PharmaDesk
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fix nested folder if exists
        run: |
          if (Test-Path pharma-desk/package.json) { Move-Item pharma-desk/* . -Force }
          dir
          cat src-tauri/tauri.conf.json

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - uses: dtolnay/rust-toolchain@stable

      - run: npm install
      - run: npm run tauri build

      - uses: actions/upload-artifact@v4
        with:
          name: PharmaDesk-Windows-Setup
          path: src-tauri/target/release/bundle/**/*.exe
